### PR TITLE
Add support for callback/callable type

### PR DESCRIPTION
**Pull request by dirx**
Playing around with rdkafka.h again... (https://github.com/ircmaxell/php-c-parser/issues/2)

Just some very basic support for callback/callable type. 
Not sure if this fits for all FunctionType variants.

### CODE REVIEW

**Comment by ircmaxell** [comment]
Should there be support for calling the callable type from PHP (so PHP can call the function pointer)?

**Comment by dirx** [comment]
Good question - their might by the following cases:

* Set PHP native callback so lib can call it (currently my case - see https://github.com/dirx/php-ffi-librdkafka/blob/master/src/RdKafka/Conf.php#L149)
* Set c native function pointer (returned from lib before) as callback so lib can call it
* Just get c native function pointer from lib and call it back from PHP

So, yes, calling a (native) callable might be a possible option. Are there concrete examples for this case?

**Comment by ircmaxell** [comment]
I'm using that case today in PHP-Compiler. I jump through some hoops for it though since I didn't support it in FFIMe. Though, having it supported here could make a ton of sense.

Here's how I'm currently working around it: https://github.com/ircmaxell/php-compiler/blob/master/lib/JIT/Result.php#L56

Note that `$address` is a void pointer in this case, and `$callbackType` is basically `void (*)(whatever function args are)`

**Comment by dirx** [comment]
"Casting" a int/size_t based address to a function pointer seems very special for your llvm case.
Just feels like I miss some deeper c knowledge here - too long ago....

Based on these variations for function pointers (the test cases...):

```c
typedef void (callback1_t)(int param11, char* param12);
void set_callback1(callback1_t *callback1);

# seems to be the "standard"
typedef void (*callback2_t)(int param21, char* param22);
void set_callback2(callback2_t callback2);

# without parenthesis
typedef void *callback2a_t(int param2a1, char* param2a2);
void set_callback2(callback2a_t callback2a);

# "anonymous" > not sure if this variation is even valid
void set_callback3(void(callback3)(int param31, char* param32));

# "anonymous"
void set_callback4(void(*callback4)(int param41, char* param42));

# callbacks that return stuff
typedef callback1_t (callback5_t)(int param51, char* param52);
void set_callback1(callback5_t *callback5);

void set_callback6(callback1_t(callback6)(int param61, char* param62));
```

Concrete function pointer types might implement __invoke (pointer only?) with concrete params (nice!):

```php
class callback1_t_ptr implements itest {
    private FFI\CData $data;
    public function __construct(FFI\CData $data) { $this->data = $data; }
    public function getData(): FFI\CData { return $this->data; }
    public function equals(callback1_t_ptr $other): bool { return $this->data == $other->data; }
    public function addr(): callback1_t_ptr_ptr { return new callback1_t_ptr_ptr(FFI::addr($this->data)); }
    public function __invoke(?int $param11, ?string $param12): void {
        $this->data($param11, $param12); // not sure if it´s that simple... this might also return stuff..
    }
    public static function getType(): string { return 'callback1_t*'; }
}
```
Usage in mapped methods might then be something like:

```php
/**
 * @param callback1_t_ptr|callable|null $callback1
 */
public function set_callback1(?callable $callback1): void
{
    $this->ffi->set_callback1($callback1 === null ? null : ($callback1 instanceof itest::class ? $callback1->getData() : $callback1));
}
```

This would allow "c native" types and plain php callables. phpdoc needed....

Not sure if a generic class for anonymous callable should be provided - it might look like this:

```php
class callable_ implements itest {
    private FFI\CData $data;
    public function __construct(FFI\CData $data) { $this->data = $data; }
    public function getData(): FFI\CData { return $this->data; }
    public function equals(callable_ $other): bool { return $this->data == $other->data; }
    public function addr(): callable__ptr { return new callable__ptr(FFI::addr($this->data)); }
    public function __invoke(...$params): void { $this->data(...$params); } // maybe this should return stuff
    public static function getType(): string { return 'void(*)()'; }
}
```

Any thoughts on this?

**Comment by bwoebi** [comment]
I'm closing this as function pointer support has been added, see for example: https://github.com/ircmaxell/FFIMe/blob/6d24ebd4cf3b92056d3905299e9e9c660d8ce3f2/test/InlineFunctions/function_pointers.php

**Pull request closed without merging**
